In [2]:
import numpy as np
import sys

In [3]:
a = [1,2,3,4,5]
b = [1,2,3,4,5]
c = np.array([1,2,3,4,5])
print(a)
print(c)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [5]:
sys. getsizeof(a)

120

In [6]:
b.nbytes

20

In [11]:
#Array 1D
d1 = np.array([1,2,3])
print(d1)
d1.shape
d1.ndim
d1.dtype

[1 2 3]


dtype('int32')

In [13]:
#Array 2D
d2 = np.array([[1,2,3], [4,5,6]])
print(d2)
d2.shape
d2.ndim
d2.dtype

[[1 2 3]
 [4 5 6]]


dtype('int32')

In [ ]:
#Array 3D
d3 = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])
print(d3)
d3.shape
d3.ndim
d3.dtype

In [3]:
#Somando Arrays
a = np.array([2,3,4])
b = np.array([2,3,4])
result =np.add(a,b)
print(result)

[4 6 8]


In [7]:
#Selecionando itens em Arrays

a = np.array([[2,3,4,5],[6,7,8,9]])
print(a)

[[2 3 4 5]
 [6 7 8 9]]


In [8]:
# Array[row,colunm)
a[1,2]

8

In [9]:
a[0,:]

array([2, 3, 4, 5])